In [10]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [12]:
%sql sqlite:///vbo.db

In [13]:
%%sql
SELECT*FROM Customers LIMIT 3;

 * sqlite:///vbo.db
Done.

[(1, 'Alfreds Futterkiste', 'Maria Anders', 'Obere Str. 57', 'Berlin', '12209', 'Germany'),
 (2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico'),
 (3, 'Antonio Moreno Taquería', 'Antonio Moreno', 'Mataderos 2312', 'México D.F.', '5023', 'Mexico')]

In [ ]:
#ORDERS TABLOSUNDAKİ MÜSTERİ SAYISI

In [16]:
%%sql
SELECT*FROM Orders  LIMIT 10;

 * sqlite:///vbo.db
Done.

[(10248, 90, 5, '4.07.1996', 3),
 (10249, 81, 6, '5.07.1996', 1),
 (10250, 34, 4, '8.07.1996', 2),
 (10251, 84, 3, '8.07.1996', 1),
 (10252, 76, 4, '9.07.1996', 2),
 (10253, 34, 3, '10.07.1996', 2),
 (10254, 14, 5, '11.07.1996', 2),
 (10255, 68, 9, '12.07.1996', 3),
 (10256, 88, 3, '15.07.1996', 2),
 (10257, 35, 4, '16.07.1996', 3)]

In [17]:
%%sql
SELECT COUNT(CustomerID) FROM Orders;

 * sqlite:///vbo.db
Done.

[(196,)]

In [ ]:
#ORDER TABLOSUNDAKİ EŞŞİZ MÜŞTERİLER

In [19]:
%%sql
SELECT COUNT(DISTINcT CustomerID) FROM Orders;

 * sqlite:///vbo.db
Done.

[(74,)]

In [20]:
##CUSTOMERS TABLOSUNDA HANGİ ÜLKEDEN KAÇAR MÜŞTERİ VAR?

In [22]:
%%sql 
SELECT COUNT(CustomerID) AS POİNT, Country FROM Customers GROUP BY Country;

 * sqlite:///vbo.db
Done.

[(3, 'Argentina'),
 (2, 'Austria'),
 (2, 'Belgium'),
 (9, 'Brazil'),
 (3, 'Canada'),
 (2, 'Denmark'),
 (2, 'Finland'),
 (11, 'France'),
 (11, 'Germany'),
 (1, 'Ireland'),
 (3, 'Italy'),
 (5, 'Mexico'),
 (1, 'Norway'),
 (1, 'Poland'),
 (2, 'Portugal'),
 (5, 'Spain'),
 (2, 'Sweden'),
 (2, 'Switzerland'),
 (7, 'UK'),
 (13, 'USA'),
 (4, 'Venezuela')]

In [23]:
%%sql
SELECT*FROM Customers WHERE Country ="Brazil" OR Country = "USA";

 * sqlite:///vbo.db
Done.

[(15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil'),
 (21, 'Familia Arquibaldo', 'Aria Cruz', 'Rua Orós, 92', 'São Paulo', '05442-030', 'Brazil'),
 (31, 'Gourmet Lanchonetes', 'André Fonseca', 'Av. Brasil, 442', 'Campinas', '04876-786', 'Brazil'),
 (32, 'Great Lakes Food Market', 'Howard Snyder', '2732 Baker Blvd.', 'Eugene', '97403', 'USA'),
 (34, 'Hanari Carnes', 'Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro', '05454-876', 'Brazil'),
 (36, 'Hungry Coyote Import Store', 'Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin', '97827', 'USA'),
 (43, 'Lazy K Kountry Store', 'John Steel', '12 Orchestra Terrace', 'Walla Walla', '99362', 'USA'),
 (45, "Let's Stop N Shop", 'Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco', '94117', 'USA'),
 (48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA'),
 (55, 'Old World Delicatessen', 'Rene Phillips', '2743 Bering St.', 'Anchorage', '99508', 'USA'),
 (61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil'),
 (62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil'),
 (65, 'Rattlesnake Canyon Grocery', 'Paula Wilson', '2817 Milton Dr.', 'Albuquerque', '87110', 'USA'),
 (67, 'Ricardo Adocicados', 'Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro', '02389-890', 'Brazil'),
 (71, 'Save-a-lot Markets', 'Jose Pavarotti', '187 Suffolk Ln.', 'Boise', '83720', 'USA'),
 (75, 'Split Rail Beer & Ale', 'Art Braunschweiger', 'P.O. Box 555', 'Lander', '82520', 'USA'),
 (77, 'The Big Cheese', 'Liz Nixon', '89 Jefferson Way Suite 2', 'Portland', '97201', 'USA'),
 (78, 'The Cracker Box', 'Liu Wong', '55 Grizzly Peak Rd.', 'Butte', '59801', 'USA'),
 (81, 'Tradição Hipermercados', 'Anabela Domingues', 'Av. Inês de Castro, 414', 'São Paulo', '05634-030', 'Brazil'),
 (82, "Trail's Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA'),
 (88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil'),
 (89, 'White Clover Markets', 'Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle', '98128', 'USA')]

In [ ]:
# Önce ülkeye sonra şehre göre group by işlemi yapıp bu kırılımda müşteri sayısını bulunuz.

In [29]:
%%sql 
SELECT COUNT(CustomerID) Country,City FROM Customers GROUP BY Country,
City;

 * sqlite:///vbo.db
Done.

[(3, 'Buenos Aires'),
 (1, 'Graz'),
 (1, 'Salzburg'),
 (1, 'Bruxelles'),
 (1, 'Charleroi'),
 (1, 'Campinas'),
 (1, 'Resende'),
 (3, 'Rio de Janeiro'),
 (4, 'São Paulo'),
 (1, 'Montréal'),
 (1, 'Tsawassen'),
 (1, 'Vancouver'),
 (1, 'København'),
 (1, 'Århus'),
 (1, 'Helsinki'),
 (1, 'Oulu'),
 (1, 'Lille'),
 (1, 'Lyon'),
 (1, 'Marseille'),
 (2, 'Nantes'),
 (2, 'Paris'),
 (1, 'Reims'),
 (1, 'Strasbourg'),
 (1, 'Toulouse'),
 (1, 'Versailles'),
 (1, 'Aachen'),
 (1, 'Berlin'),
 (1, 'Brandenburg'),
 (1, 'Cunewalde'),
 (1, 'Frankfurt a.M.'),
 (1, 'Köln'),
 (1, 'Leipzig'),
 (1, 'Mannheim'),
 (1, 'München'),
 (1, 'Münster'),
 (1, 'Stuttgart'),
 (1, 'Cork'),
 (1, 'Bergamo'),
 (1, 'Reggio Emilia'),
 (1, 'Torino'),
 (5, 'México D.F.'),
 (1, 'Stavern'),
 (1, 'Walla'),
 (2, 'Lisboa'),
 (1, 'Barcelona'),
 (3, 'Madrid'),
 (1, 'Sevilla'),
 (1, 'Bräcke'),
 (1, 'Luleå'),
 (1, 'Bern'),
 (1, 'Genève'),
 (1, 'Cowes'),
 (6, 'London'),
 (1, 'Albuquerque'),
 (1, 'Anchorage'),
 (1, 'Boise'),
 (1, 'Butte'),
 (1, 'Elgin'),
 (1, 'Eugene'),
 (1, 'Kirkland'),
 (1, 'Lander'),
 (2, 'Portland'),
 (1, 'San Francisco'),
 (1, 'Seattle'),
 (1, 'Walla Walla'),
 (1, 'Barquisimeto'),
 (1, 'Caracas'),
 (1, 'I. de Margarita'),
 (1, 'San Cristóbal')]

In [30]:
#Müşteriler adreslerinin herhangi bir yerinde "da " ifadesi geçen tüm adresler

In [36]:
%%sql
SELECT*FROM Customers WHERE Address LIKE '%da%';

 * sqlite:///vbo.db
Done.

[(2, 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Avda. de la Constitución 2222', 'México D.F.', '5021', 'Mexico'),
 (13, 'Centro comercial Moctezuma', 'Francisco Chang', 'Sierras de Granada 9993', 'México D.F.', '5022', 'Mexico'),
 (15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil'),
 (28, 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa', '1675', 'Portugal'),
 (54, 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', '1010', 'Argentina'),
 (60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal'),
 (61, 'Que Delícia', 'Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro', '02389-673', 'Brazil'),
 (62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil'),
 (66, 'Reggiani Caseifici', 'Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia', '42100', 'Italy'),
 (80, 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Avda. Azteca 123', 'México D.F.', '5033', 'Mexico'),
 (82, "Trail's Head Gourmet Provisioners", 'Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland', '98034', 'USA')]

In [ ]:
 # Germany-Berlin'de yaşayan müşteri/müşterilerin isimleri nelerdir?

In [46]:
%%sql
SELECT CustomerName FROM Customers  WHERE Country= "Germany" AND City = "Berlin";

 * sqlite:///vbo.db
Done.

[('Alfreds Futterkiste',)]

In [ ]:
 # Canada'da yaşayıp isimlerinde "in" ifadesi geçen müşteri/müşterileri bulunuz.

In [47]:
%%sql 
SELECT*FROM Customers WHERE CustomerName LIKE "%in%";

 * sqlite:///vbo.db
Done.

[(14, 'Chop-suey Chinese', 'Yang Wang', 'Hauptstr. 29', 'Bern', '3012', 'Switzerland'),
 (15, 'Comércio Mineiro', 'Pedro Afonso', 'Av. dos Lusíadas, 23', 'São Paulo', '05432-043', 'Brazil'),
 (16, 'Consolidated Holdings', 'Elizabeth Brown', 'Berkeley Gardens 12 Brewery', 'London', 'WX1 6LT', 'UK'),
 (22, 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'C/ Moralzarzal, 86', 'Madrid', '28034', 'Spain'),
 (30, 'Godos Cocina Típica', 'José Pedro Freyre', 'C/ Romero, 33', 'Sevilla', '41101', 'Spain'),
 (38, 'Island Trading', 'Helen Bennett', 'Garden House Crowther Way', 'Cowes', 'PO31 7PJ', 'UK'),
 (42, 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '1900 Oak St.', 'Vancouver', 'V3F 2K1', 'Canada'),
 (47, 'LINO-Delicateses', 'Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', '4980', 'Venezuela'),
 (48, 'Lonesome Pine Restaurant', 'Fran Wilson', '89 Chiaroscuro Rd.', 'Portland', '97219', 'USA'),
 (49, 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo', '24100', 'Italy'),
 (60, 'Princesa Isabel Vinhoss', 'Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa', '1756', 'Portugal'),
 (62, 'Queen Cozinha', 'Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'São Paulo', '05487-020', 'Brazil'),
 (85, 'Vins et alcools Chevalier', 'Paul Henriot', "59 rue de l'Abbaye", 'Reims', '51100', 'France'),
 (88, 'Wellington Importadora', 'Paula Parente', 'Rua do Mercado, 12', 'Resende', '08737-363', 'Brazil')]

In [ ]:
# Fiyatı 40 TL ile 90 TL arasında olan ürünlerin isimleri ve fiyatları nelerdir?

In [48]:
%%sql
SELECT ProductName, Price FROM Products WHERE Price<90 AND Price>40;

 * sqlite:///vbo.db
Done.

[('Genen Shouyu', 43),
 ('Carnarvon Tigers', 62),
 ('Teatime Chocolate Biscuits', 43),
 ("Sir Rodney's Marmalade", 81),
 ('Guaraná Fantástica', 43),
 ('Schoggi Schokolade', 43),
 ('Rössle Sauerkraut', 45),
 ('Geitost', 43),
 ('Boston Crab Meat', 43),
 ('Ipoh Coffee', 46),
 ('Røgede sild', 43),
 ('Zaanse koeken', 43),
 ('Manjimup Dried Apples', 53),
 ('Ravioli Angelo', 43),
 ('Raclette Courdavault', 55),
 ("Sirop d'érable", 43),
 ('Tarte au sucre', 49),
 ('Vegie-spread', 43),
 ('Louisiana Fiery Hot Pepper Sauce', 43),
 ('Scottish Longbreads', 45)]

In [ ]:
# Fiyatı 30 TL'den büyük olan ürünlerin isimlerini, fiyatlarını ve fiyatlarının karesini bulunuz ve tüm değişkenlerin isimlendirmelerini aşağıdaki şekilde yapınız:

# urun ismi, urun_fiyati, ürün_fiyatinin_karesi

In [50]:
%%sql
SELECT ProductName AS ÜRÜN_İSMİ, Price AS Fiyat, Price*Price AS Karesi FROM Products WHERE Price>30;

 * sqlite:///vbo.db
Done.

[('Northwoods Cranberry Sauce', 40, 1600),
 ('Mishi Kobe Niku', 97, 9409),
 ('Ikura', 31, 961),
 ('Queso Manchego La Pastora', 38, 1444),
 ('Genen Shouyu', 43, 1849),
 ('Alice Mutton', 39, 1521),
 ('Carnarvon Tigers', 62, 3844),
 ('Teatime Chocolate Biscuits', 43, 1849),
 ("Sir Rodney's Marmalade", 81, 6561),
 ('Guaraná Fantástica', 43, 1849),
 ('Gumbär Gummibärchen', 31, 961),
 ('Schoggi Schokolade', 43, 1849),
 ('Rössle Sauerkraut', 45, 2025),
 ('Thüringer Rostbratwurst', 123, 15129),
 ('Gorgonzola Telino', 435, 189225),
 ('Mascarpone Fabioli', 32, 1024),
 ('Geitost', 43, 1849),
 ('Côte de Blaye', 263, 69169),
 ('Boston Crab Meat', 43, 1849),
 ('Ipoh Coffee', 46, 2116),
 ('Røgede sild', 43, 1849),
 ('Zaanse koeken', 43, 1849),
 ('Manjimup Dried Apples', 53, 2809),
 ('Perth Pasties', 32, 1024),
 ('Gnocchi di nonna Alice', 38, 1444),
 ('Ravioli Angelo', 43, 1849),
 ('Raclette Courdavault', 55, 3025),
 ('Camembert Pierrot', 34, 1156),
 ("Sirop d'érable", 43, 1849),
 ('Tarte au sucre', 49, 2401),
 ('Vegie-spread', 43, 1849),
 ('Wimmers gute Semmelknödel', 33, 1089),
 ('Louisiana Fiery Hot Pepper Sauce', 43, 1849),
 ('Scottish Longbreads', 45, 2025),
 ('Gudbrandsdalsost', 36, 1296),
 ('Mozzarella di Giovanni', 34, 1156)]

In [ ]:
# Products tablosundaki CategoryID’lerin yani kategorilerin isimleri nelerdir?

In [52]:
%%sql 
SELECT ProductName, CategoryID FROM Products;

 * sqlite:///vbo.db
Done.

[('Chais', 1),
 ('Chang', 1),
 ('Aniseed Syrup', 2),
 ("Chef Anton's Cajun Seasoning", 2),
 ("Chef Anton's Gumbo Mix", 2),
 ("Grandma's Boysenberry Spread", 2),
 ("Uncle Bob's Organic Dried Pears", 7),
 ('Northwoods Cranberry Sauce', 2),
 ('Mishi Kobe Niku', 6),
 ('Ikura', 8),
 ('Queso Cabrales', 4),
 ('Queso Manchego La Pastora', 4),
 ('Konbu', 8),
 ('Tofu', 7),
 ('Genen Shouyu', 2),
 ('Pavlova', 3),
 ('Alice Mutton', 6),
 ('Carnarvon Tigers', 8),
 ('Teatime Chocolate Biscuits', 3),
 ("Sir Rodney's Marmalade", 3),
 ("Sir Rodney's Scones", 3),
 ("Gustaf's Knäckebröd", 5),
 ('Tunnbröd', 5),
 ('Guaraná Fantástica', 1),
 ('NuNuCa Nuß-Nougat-Creme', 3),
 ('Gumbär Gummibärchen', 3),
 ('Schoggi Schokolade', 3),
 ('Rössle Sauerkraut', 7),
 ('Thüringer Rostbratwurst', 6),
 ('Nord-Ost Matjeshering', 8),
 ('Gorgonzola Telino', 4),
 ('Mascarpone Fabioli', 4),
 ('Geitost', 4),
 ('Sasquatch Ale', 1),
 ('Steeleye Stout', 1),
 ('Inlagd Sill', 8),
 ('Gravad lax', 8),
 ('Côte de Blaye', 1),
 ('Chartreuse verte', 1),
 ('Boston Crab Meat', 8),
 ("Jack's New England Clam Chowder", 8),
 ('Singaporean Hokkien Fried Mee', 5),
 ('Ipoh Coffee', 1),
 ('Gula Malacca', 2),
 ('Røgede sild', 8),
 ('Spegesild', 8),
 ('Zaanse koeken', 3),
 ('Chocolade', 3),
 ('Maxilaku', 3),
 ('Valkoinen suklaa', 3),
 ('Manjimup Dried Apples', 7),
 ('Filo Mix', 5),
 ('Perth Pasties', 6),
 ('Tourtière', 6),
 ('Pâté chinois', 6),
 ('Gnocchi di nonna Alice', 5),
 ('Ravioli Angelo', 5),
 ('Escargots de Bourgogne', 8),
 ('Raclette Courdavault', 4),
 ('Camembert Pierrot', 4),
 ("Sirop d'érable", 2),
 ('Tarte au sucre', 3),
 ('Vegie-spread', 2),
 ('Wimmers gute Semmelknödel', 5),
 ('Louisiana Fiery Hot Pepper Sauce', 2),
 ('Louisiana Hot Spiced Okra', 2),
 ('Laughing Lumberjack Lager', 1),
 ('Scottish Longbreads', 3),
 ('Gudbrandsdalsost', 4),
 ('Outback Lager', 1),
 ('Fløtemysost', 4),
 ('Mozzarella di Giovanni', 4),
 ('Röd Kaviar', 8),
 ('Longlife Tofu', 7),
 ('Rhönbräu Klosterbier', 1),
 ('Lakkalikööri', 1),
 ('Original Frankfurter grüne Soße', 2)]

In [53]:
%%sql
SELECT * 
FROM Products 
LEFT JOIN Categories on Products.CategoryID = Categories.CategoryID;

 * sqlite:///vbo.db
Done.

[(1, 'Chais', 1, 1, '10 boxes x 20 bags', 18, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (2, 'Chang', 1, 1, '24 - 12 oz bottles', 19, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (3, 'Aniseed Syrup', 1, 2, '12 - 550 ml bottles', 10, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (4, "Chef Anton's Cajun Seasoning", 2, 2, '48 - 6 oz jars', 22, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (5, "Chef Anton's Gumbo Mix", 2, 2, '36 boxes', 21, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (6, "Grandma's Boysenberry Spread", 3, 2, '12 - 8 oz jars', 25, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (7, "Uncle Bob's Organic Dried Pears", 3, 7, '12 - 1 lb pkgs.', 30, 7, 'Produce', 'Dried fruit and bean curd'),
 (8, 'Northwoods Cranberry Sauce', 3, 2, '12 - 12 oz jars', 40, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (9, 'Mishi Kobe Niku', 4, 6, '18 - 500 g pkgs.', 97, 6, 'Meat/Poultry', 'Prepared meats'),
 (10, 'Ikura', 4, 8, '12 - 200 ml jars', 31, 8, 'Seafood', 'Seaweed and fish'),
 (11, 'Queso Cabrales', 5, 4, '1 kg pkg.', 21, 4, 'Dairy Products', 'Cheeses'),
 (12, 'Queso Manchego La Pastora', 5, 4, '10 - 500 g pkgs.', 38, 4, 'Dairy Products', 'Cheeses'),
 (13, 'Konbu', 6, 8, '2 kg box', 6, 8, 'Seafood', 'Seaweed and fish'),
 (14, 'Tofu', 6, 7, '40 - 100 g pkgs.', 23, 7, 'Produce', 'Dried fruit and bean curd'),
 (15, 'Genen Shouyu', 6, 2, '24 - 250 ml bottles', 43, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (16, 'Pavlova', 7, 3, '32 - 500 g boxes', 17, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (17, 'Alice Mutton', 7, 6, '20 - 1 kg tins', 39, 6, 'Meat/Poultry', 'Prepared meats'),
 (18, 'Carnarvon Tigers', 7, 8, '16 kg pkg.', 62, 8, 'Seafood', 'Seaweed and fish'),
 (19, 'Teatime Chocolate Biscuits', 8, 3, '10 boxes x 12 pieces', 43, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (20, "Sir Rodney's Marmalade", 8, 3, '30 gift boxes', 81, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (21, "Sir Rodney's Scones", 8, 3, '24 pkgs. x 4 pieces', 10, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (22, "Gustaf's Knäckebröd", 9, 5, '24 - 500 g pkgs.', 21, 5, 'Grains/Cereals', 'Breads, crackers, pasta, and cereal'),
 (23, 'Tunnbröd', 9, 5, '12 - 250 g pkgs.', 9, 5, 'Grains/Cereals', 'Breads, crackers, pasta, and cereal'),
 (24, 'Guaraná Fantástica', 10, 1, '12 - 355 ml cans', 43, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (25, 'NuNuCa Nuß-Nougat-Creme', 11, 3, '20 - 450 g glasses', 14, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (26, 'Gumbär Gummibärchen', 11, 3, '100 - 250 g bags', 31, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (27, 'Schoggi Schokolade', 11, 3, '100 - 100 g pieces', 43, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (28, 'Rössle Sauerkraut', 12, 7, '25 - 825 g cans', 45, 7, 'Produce', 'Dried fruit and bean curd'),
 (29, 'Thüringer Rostbratwurst', 12, 6, '50 bags x 30 sausgs.', 123, 6, 'Meat/Poultry', 'Prepared meats'),
 (30, 'Nord-Ost Matjeshering', 13, 8, '10 - 200 g glasses', 25, 8, 'Seafood', 'Seaweed and fish'),
 (31, 'Gorgonzola Telino', 14, 4, '12 - 100 g pkgs', 435, 4, 'Dairy Products', 'Cheeses'),
 (32, 'Mascarpone Fabioli', 14, 4, '24 - 200 g pkgs.', 32, 4, 'Dairy Products', 'Cheeses'),
 (33, 'Geitost', 15, 4, '500 g', 43, 4, 'Dairy Products', 'Cheeses'),
 (34, 'Sasquatch Ale', 16, 1, '24 - 12 oz bottles', 14, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (35, 'Steeleye Stout', 16, 1, '24 - 12 oz bottles', 18, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (36, 'Inlagd Sill', 17, 8, '24 - 250 g jars', 19, 8, 'Seafood', 'Seaweed and fish'),
 (37, 'Gravad lax', 17, 8, '12 - 500 g pkgs.', 26, 8, 'Seafood', 'Seaweed and fish'),
 (38, 'Côte de Blaye', 18, 1, '12 - 75 cl bottles', 263, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (39, 'Chartreuse verte', 18, 1, '750 cc per bottle', 18, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (40, 'Boston Crab Meat', 19, 8, '24 - 4 oz tins', 43, 8, 'Seafood', 'Seaweed and fish'),
 (41, "Jack's New England Clam Chowder", 19, 8, '12 - 12 oz cans', 23, 8, 'Seafood', 'Seaweed and fish'),
 (42, 'Singaporean Hokkien Fried Mee', 20, 5, '32 - 1 kg pkgs.', 14, 5, 'Grains/Cereals', 'Breads, crackers, pasta, and cereal'),
 (43, 'Ipoh Coffee', 20, 1, '16 - 500 g tins', 46, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (44, 'Gula Malacca', 20, 2, '20 - 2 kg bags', 19, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (45, 'Røgede sild', 21, 8, '1k pkg.', 43, 8, 'Seafood', 'Seaweed and fish'),
 (46, 'Spegesild', 21, 8, '4 - 450 g glasses', 12, 8, 'Seafood', 'Seaweed and fish'),
 (47, 'Zaanse koeken', 22, 3, '10 - 4 oz boxes', 43, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (48, 'Chocolade', 22, 3, '10 pkgs.', 27, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (49, 'Maxilaku', 23, 3, '24 - 50 g pkgs.', 20, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (50, 'Valkoinen suklaa', 23, 3, '12 - 100 g bars', 16, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (51, 'Manjimup Dried Apples', 24, 7, '50 - 300 g pkgs.', 53, 7, 'Produce', 'Dried fruit and bean curd'),
 (52, 'Filo Mix', 24, 5, '16 - 2 kg boxes', 7, 5, 'Grains/Cereals', 'Breads, crackers, pasta, and cereal'),
 (53, 'Perth Pasties', 24, 6, '48 pieces', 32, 6, 'Meat/Poultry', 'Prepared meats'),
 (54, 'Tourtière', 25, 6, '16 pies', 16, 6, 'Meat/Poultry', 'Prepared meats'),
 (55, 'Pâté chinois', 25, 6, '24 boxes x 2 pies', 24, 6, 'Meat/Poultry', 'Prepared meats'),
 (56, 'Gnocchi di nonna Alice', 26, 5, '24 - 250 g pkgs.', 38, 5, 'Grains/Cereals', 'Breads, crackers, pasta, and cereal'),
 (57, 'Ravioli Angelo', 26, 5, '24 - 250 g pkgs.', 43, 5, 'Grains/Cereals', 'Breads, crackers, pasta, and cereal'),
 (58, 'Escargots de Bourgogne', 27, 8, '24 pieces', 13, 8, 'Seafood', 'Seaweed and fish'),
 (59, 'Raclette Courdavault', 28, 4, '5 kg pkg.', 55, 4, 'Dairy Products', 'Cheeses'),
 (60, 'Camembert Pierrot', 28, 4, '15 - 300 g rounds', 34, 4, 'Dairy Products', 'Cheeses'),
 (61, "Sirop d'érable", 29, 2, '24 - 500 ml bottles', 43, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (62, 'Tarte au sucre', 29, 3, '48 pies', 49, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (63, 'Vegie-spread', 7, 2, '15 - 625 g jars', 43, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (64, 'Wimmers gute Semmelknödel', 12, 5, '20 bags x 4 pieces', 33, 5, 'Grains/Cereals', 'Breads, crackers, pasta, and cereal'),
 (65, 'Louisiana Fiery Hot Pepper Sauce', 2, 2, '32 - 8 oz bottles', 43, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (66, 'Louisiana Hot Spiced Okra', 2, 2, '24 - 8 oz jars', 17, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 (67, 'Laughing Lumberjack Lager', 16, 1, '24 - 12 oz bottles', 14, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (68, 'Scottish Longbreads', 8, 3, '10 boxes x 8 pieces', 45, 3, 'Confections', 'Desserts, candies, and sweet breads'),
 (69, 'Gudbrandsdalsost', 15, 4, '10 kg pkg.', 36, 4, 'Dairy Products', 'Cheeses'),
 (70, 'Outback Lager', 7, 1, '24 - 355 ml bottles', 15, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (71, 'Fløtemysost', 15, 4, '10 - 500 g pkgs.', 21, 4, 'Dairy Products', 'Cheeses'),
 (72, 'Mozzarella di Giovanni', 14, 4, '24 - 200 g pkgs.', 34, 4, 'Dairy Products', 'Cheeses'),
 (73, 'Röd Kaviar', 17, 8, '24 - 150 g jars', 15, 8, 'Seafood', 'Seaweed and fish'),
 (74, 'Longlife Tofu', 4, 7, '5 kg pkg.', 10, 7, 'Produce', 'Dried fruit and bean curd'),
 (75, 'Rhönbräu Klosterbier', 12, 1, '24 - 0.5 l bottles', 27, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (76, 'Lakkalikööri', 23, 1, '500 ml', 18, 1, 'Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 (77, 'Original Frankfurter grüne Soße', 12, 2, '12 boxes', 13, 2, 'Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings')]

In [54]:
# beverages ürün kategorisindeki ürünlerin fiyat ortalaması nedir?

In [57]:
%%sql
SELECT AVG(Price) FROM Products WHERE CategoryID =1;

 * sqlite:///vbo.db
Done.

[(42.75,)]

In [58]:

%%sql
SELECT AVG(Price) 
FROM Products 
LEFT JOIN Categories on Products.CategoryID = categories.CategoryID 
WHERE CategoryName = 'Beverages';

 * sqlite:///vbo.db
Done.

[(42.75,)]

In [59]:
# USA'de yaşayan müşterilerin kazandırdığı toplam kazancı bulunuz.

In [61]:
%%sql 
SELECT SUM(p.Price) 
FROM Orders o 
LEFT JOIN OrderDetails od on o.OrderID = od.OrderID 
LEFT JOIN Products p on od.ProductID = p.ProductID 
LEFT JOIN Customers cu on o.CustomerID = cu.CustomerID where cu.Country = 'USA';

 * sqlite:///vbo.db
Done.

[(3762,)]